"""empty message

Revision ID: 1292d55af02a
Revises: 
Create Date: 2024-01-24 11:42:02.326582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1292d55af02a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
