"""empty message

Revision ID: 144f61d22978
Revises: 49869bdd4784
Create Date: 2024-04-04 12:43:55.879550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144f61d22978'
down_revision = '49869bdd4784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line1', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('postcode')
        batch_op.drop_column('city')
        batch_op.drop_column('province')
        batch_op.drop_column('address_line1')

    # ### end Alembic commands ###
